<?php

use Drupal\system_status\Controller\SystemStatusEncryption;

/**
 * @file
 * Installation file for system_status.
 */

/**
 * Implements hook_install().
 *
 * Creates a unique set of tokens for this installation.
 */
function system_status_install() {
  $config = \Drupal::config('system_status.settings');
  $config->set('system_status_token', SystemStatusEncryption::getToken());
  $config->set('system_status_encrypt_token', SystemStatusEncryption::getToken());
  $config->save();
}
